version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
  - package-ecosystem: "gradle"
    directory: /
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
    groups:
      androidx:
        patterns: ["androidx*"]
      kotlin:
        patterns: ["org.jetbrains.kotlin*"]
  - package-ecosystem: "npm"
    directory: /worker
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
