build:
  maxIssues: 0

config:
  validation: true

style:
  MaxLineLength:
    maxLineLength: 140
  MagicNumber:
    active: false
  ReturnCount:
    max: 4

complexity:
  TooManyFunctions:
    thresholdInClasses: 25
    thresholdInObjects: 25

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

naming:
  FunctionNaming:
    functionPattern: "[a-zA-Z][a-zA-Z0-9]*"
