package com.kanarek.data

// Generated by .github/scripts/sync-default-feeds.mjs from worker/wrangler.jsonc.
// Edit vars.DEFAULT_FEEDS there, then run: node .github/scripts/sync-default-feeds.mjs
object DefaultFeeds {
    val urls: List<String> =
        listOf(
            "https://news.google.com/atom?hl=pl&gl=PL&ceid=PL:pl",
            "https://pl.euronews.com/rss?format=mrss",
            "https://antyweb.pl/feed/",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_pap.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_reuters.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_wikipedia_pl.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_daily_digest.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_daily_quote.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_jbzd.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_beatport_top100.xml",
            "https://raw.githubusercontent.com/trvny/feedseek/main/feeds/feed_cloudflare.xml",
        )
}
